image: docker:latest

before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${DOCKER_ENV_CI_REGISTRY}

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TRANSIENT: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  IMAGE_RELEASE: ${CI_REGISTRY_IMAGE}/release:${CI_BUILD_REF_NAME}

stages:
  - build
  - test
  - publish
  - deploy


build:
  stage: build
  services:
    - name: docker:dind
  script:
    - docker build -t ${IMAGE_TRANSIENT} .
    - docker push ${IMAGE_TRANSIENT}

unit:
  stage: test
  services:
    - name: docker:dind
  script:
    - docker run ${IMAGE_TRANSIENT} npm run test

style:
  stage: test
  services:
    - name: docker:dind
  script:
    - docker run ${IMAGE_TRANSIENT} npm run eslint

# integration:
#   stage: test
#   image: spokedev/whale:latest
#   services:
#     - name: docker:dind
#   script:
#     - ./build/scripts/up env-integration
#     - docker run ${IMAGE_TRANSIENT} npm run test:feature
#     - docker run ${IMAGE_TRANSIENT} npm run test:performance
#   after_script:
#     - ./build/scripts/down env-integration
#   environment:
#     name: transient/${CI_COMMIT_SHA}
#   only:
#     - /^v\d+\.\d+\.\d+$/
#   except:
#     - /^(?!.*(master|v?\d+\.\d+\.\d+)$).*$/

publish:
  stage: publish
  services:
    - name: docker:dind
  script:
    - docker pull ${IMAGE_TRANSIENT}
    - docker tag ${IMAGE_TRANSIENT} ${IMAGE_RELEASE}
    - docker push ${IMAGE_RELEASE}
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - /^(?!.*(master|v?\d+\.\d+\.\d+)$).*$/

deploy_dev:
  stage: deploy
  image: spokedev/whale:latest
  services:
    - name: docker:dind
  script:
    - scripts/deploy_dev
  when: manual
  environment:
    name: dev
    on_stop: destroy_dev
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - /^(?!.*(master|v?\d+\.\d+\.\d+)$).*$/

destroy_dev:
  stage: deploy
  image: spokedev/whale:latest
  services:
    - name: docker:dind
  script:
    - scripts/destroy_dev
  when: manual
  environment:
    name: dev
    action: stop
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - /^(?!.*(master|v?\d+\.\d+\.\d+)$).*$/
