stages:
  - install
  - test
  - publish

install:
  stage: install
  image: node:8.10.0
  artifacts:
    paths:
      - node_modules/
    expire_in: 15mins
  script:
    - npm i

unit:
  stage: test
  image: node:8.10.0
  dependencies:
    - install
  script:
    - npm run test:unit

style:
  stage: test
  image: node:8.10.0
  dependencies:
    - install
  script:
    - npm run lint

# publish:
#   image: docker:latest
#   services:
#    - docker:dind
#   stage: publish
#   script:
#     - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${DOCKER_ENV_CI_REGISTRY}
#     - docker build -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME} .
#     - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}
#   only:
#     - /^v\d+\.\d+\.\d+$/
#   except:
#     - /^(?!.*(master|v?\d+\.\d+\.\d+)$).*$/

publish_dev:
  image: docker:latest
  services:
   - docker:dind
  stage: publish
  script:
    - export ENV_NAME=erebusdev
    - "./scripts/deploy"
  only:
    - master
  artifacts:
    paths:
    - deployment-erebusdev.yaml
    expire_in: 5 yrs


publish_staging:
  image: docker:latest
  services:
   - docker:dind
  stage: publish
  script:
    - export ENV_NAME=erebusstaging
    - ./scripts/deploy
  only:
    - staging
  artifacts:
    paths:
    - deployment-erebusstaging.yaml
    expire_in: 5 yrs


publish_release:
  image: docker:latest
  services:
   - docker:dind
  stage: publish
  script:
    - export ENV_NAME=erebus
    - ./scripts/deploy
  only:
    - release
  artifacts:
    paths:
    - deployment-erebus.yaml
    expire_in: 5 yrs
