apiVersion: v1
kind: Service
metadata:
  labels:
    app: gettingstarted-${ENV_NAME}
  name: gettingstarted-${ENV_NAME}
  namespace: fab-${ENV_NAME}
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
    protocol: TCP
  selector:
    app: gettingstarted-${ENV_NAME}
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gettingstarted-${ENV_NAME}
  namespace: fab-${ENV_NAME}
  labels:
    app: gettingstarted-${ENV_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gettingstarted-${ENV_NAME}
  template:
    metadata:
      labels:
        app: gettingstarted-${ENV_NAME}
    spec:
      containers:
      - name: gettingstarted-${ENV_NAME}
        image: ${IMAGE_RELEASE}
        imagePullPolicy: Always
        # volumeMounts: # Only needed if bluemix service (eg, DB2) access is needed
        # - mountPath: /opt/service-bind
        #   name: service-bind-volume
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            memory: "250Mi"
          limits:
            memory: "500Mi"
        env:
        - name: ENV_NAME
          value: "${ENV_NAME}"
        - name: DAS_URL
          value: "${DAS_URL}"
        - name: DAS_CLIENT_ID
          value: "${DAS_CLIENT_ID}"
        - name: DAS_CLIENT_SECRET
          value: "${DAS_CLIENT_SECRET}"
      # volumes: # Only needed if bluemix service (eg, DB2) access is needed
      # - name: service-bind-volume
      #   secret:
      #     defaultMode: 420
      #     secretName: binding-fab-ods-dev
      imagePullSecrets:
      - name: regcred
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gettingstarted-${ENV_NAME}
  namespace: fab-${ENV_NAME}
spec:
  rules:
  - host: gettingstarted.${ENV_NAME}.${TARGET_URL_BASE}
    http:
      paths:
      - path: /gettingstarted # Must match basePath in API definition yaml
        backend:
          serviceName: gettingstarted-${ENV_NAME}
          servicePort: 3000
