swagger: '2.0'
info:
  x-ibm-name: gettingstarted
  version: 1.0.0
  title: gettingstarted
schemes:
  - https
host: $(catalog.host)
basePath: /gettingstarted # Must match ingress path in deploy/deployment.yaml
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: 'http://gettingstarted.${ENV_NAME}.${TARGET_URL_BASE}$(request.path)$(request.search)'
paths:
  '/ping':
    get:
      tags:
        - Ping
      summary: Test the reachability of the microserver.
      operationId: Ping
      responses:
        '200':
          description: Microservice is alive
      deprecated: false
  '/ready':
    get:
      tags:
        - Ready
      summary: Provides the readiness of the microservice to process requests.
      operationId: Ready
      responses:
        '200':
          description: Request was successful
      deprecated: false
  '/faqs':
    get:
      tags:
        - FAQs
      summary: Get FAQs.
      description: Returns a list of FAQs.
      operationId: faqs.get
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/faq'
definitions:
  faq:
    required:
      - FAQID
    properties:
      FAQID:
        description: Unique faq identifier
        type: string
        format: uuid
      question:
        description: Question being asked
        type: string
      answer:
        description: The answer to the question
        type: string
      lastUpdated:
        description: The date/time that a faq was last modified
        type: string
        # format: date-time
      lastUpdateBy:
        description: The name of the user that last updated the faq
        type: string
